version: '3.4'

services:
  mizekar.idea.micro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - dbconnection=Server=db;Database=Mizekar.Idea;User Id=sa;Password=MyStrong_*123456;MultipleActiveResultSets=True
    ports:
      - "63091:80"
      - "44399:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
networks:
  default:
    external:
      name: nat